//go:build e2e

package hermetic

import (
	"strings"
	"testing"
)

// Translator block — covers rc.4 (built-in mirror) and rc.5 (default-on).

func TestTranslator_InitProducesMirroredClaudeMD(t *testing.T) {
	p := newProject(t)
	if !p.fileExists("CLAUDE.md") {
		t.Fatal("expected CLAUDE.md at project root after init")
	}
	body := p.readFile("CLAUDE.md")
	if !strings.HasPrefix(body, "<!-- Auto-generated by Samuel (Claude translator)") {
		t.Errorf("CLAUDE.md missing translator marker; got %q", body)
	}
}

func TestTranslator_RegeneratesAfterDelete(t *testing.T) {
	p := newProject(t)
	p.rmFile("CLAUDE.md")
	out := p.mustSamuel("sync")
	assertContains(t, out, "create CLAUDE.md", "sync should recreate the mirror")
	if !p.fileExists("CLAUDE.md") {
		t.Error("sync did not restore CLAUDE.md")
	}
}

func TestTranslator_PropagatesAgentsMDChanges(t *testing.T) {
	p := newProject(t)
	agents := p.readFile("AGENTS.md")
	p.writeFile("AGENTS.md", agents+"\n\n## Sentinel\ne2e-sentinel-9d3f7a2e\n")
	out := p.mustSamuel("sync")
	assertContains(t, out, "update CLAUDE.md", "AGENTS.md mutation should trigger mirror update")
	assertContains(t, p.readFile("CLAUDE.md"), "e2e-sentinel-9d3f7a2e", "sentinel must reach the mirror")
}

func TestTranslator_PreservesUserCustomizedClaudeMD(t *testing.T) {
	p := newProject(t)
	custom := "Hand-edited — must survive sync\n"
	p.writeFile("CLAUDE.md", custom)
	out := p.mustSamuel("sync")
	assertContains(t, out, "skip CLAUDE.md (user-customized)", "user-customized file should be skipped")
	if got := p.readFile("CLAUDE.md"); got != custom {
		t.Errorf("user-customized file was modified: %q", got)
	}
}

func TestTranslator_DefaultOnWhenConfigSectionAbsent(t *testing.T) {
	// rc.5 regression: pre-rc.4-era samuel.toml has no
	// [translators.claude] section. Translator must still run.
	p := newProject(t)
	// Strip the [translators.claude] section to simulate the old toml.
	toml := p.readFile("samuel.toml")
	// Crude but sufficient: cut from "[translators" to EOF.
	if idx := strings.Index(toml, "[translators"); idx != -1 {
		toml = strings.TrimRight(toml[:idx], "\n") + "\n"
	}
	p.writeFile("samuel.toml", toml)
	p.rmFile("CLAUDE.md")
	out := p.mustSamuel("sync")
	assertContains(t, out, "create CLAUDE.md", "absent translators section must default-on")
}
