#!/usr/bin/env bash
# Ensure .github/workflows/release.yml exists on a plugin repo, pointing at
# samuelpkg/samuel-plugin-release. If the file is already present and
# correct, exit clean. If it's missing, create it. If it references the old
# ar4mirez owner, patch it.
#
# Companion to patch-plugin-workflow.sh — that one only updates an existing
# file. This one handles the create-if-missing case too.
#
# Usage:
#   ./scripts/ensure-plugin-workflow.sh samuel-uikit

set -e

repo="$1"
if [ -z "$repo" ]; then
  echo "usage: $0 <repo-name>" >&2
  exit 64
fi

owner="${OWNER:-samuelpkg}"
path=".github/workflows/release.yml"

# Canonical workflow content — must stay in sync with the migration script.
canonical=$(cat <<'YML'
# Generated by scripts/migrate-v1-skills. Plugin authors should keep this
# file in sync with samuel-plugin-release's latest stable tag.
name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write
  id-token: write   # cosign keyless signing

jobs:
  release:
    uses: samuelpkg/samuel-plugin-release/.github/workflows/release.yml@v1
    with:
      manifest: samuel-plugin.toml
    secrets: inherit
YML
)
new_b64=$(printf '%s\n' "$canonical" | base64 | tr -d '\n')

resp=$(/opt/homebrew/bin/gh api "repos/$owner/$repo/contents/$path" 2>/dev/null || echo "")

if [ -z "$resp" ] || [[ "$resp" == *'"status":"404"'* ]]; then
  # File missing — create.
  /opt/homebrew/bin/gh api -X PUT "repos/$owner/$repo/contents/$path" \
    -f message="chore: add release workflow (was missing)" \
    -f content="$new_b64" \
    --jq '"  created: \(.content.path) @ \(.commit.sha[0:7])"' 2>&1 | tail -1
  exit 0
fi

sha=$(printf '%s' "$resp" | jq -r '.sha')
decoded=$(printf '%s' "$resp" | jq -r '.content' | base64 -d 2>/dev/null)

if [[ "$decoded" == *"samuelpkg/samuel-plugin-release"* ]]; then
  echo "  skip: $repo (already canonical)"
  exit 0
fi

# Update existing file.
/opt/homebrew/bin/gh api -X PUT "repos/$owner/$repo/contents/$path" \
  -f message="chore: repoint release workflow to samuelpkg/samuel-plugin-release" \
  -f content="$new_b64" \
  -f sha="$sha" \
  --jq '"  patched: \(.content.path) @ \(.commit.sha[0:7])"' 2>&1 | tail -1
