#!/usr/bin/env bash
# Push a single migration-output/samuel-<name> tree to <owner>/samuel-<name>.
# Idempotent: safe to re-run when partial state exists from a previous attempt.
#
# Important properties:
#   - Always re-stages the working tree (`git add -A`) and only commits when
#     there's actual drift. The earlier "skip git block if .git exists" path
#     silently dropped .github/ and references/ for plugins whose first
#     attempt half-completed; this helper has no such trap.
#   - Tags v1.0.0 once; subsequent runs are no-ops if the tag is already there.
#   - Caps the GitHub repo description at 340 chars (GitHub's createRepository
#     mutation rejects >350). The full original text stays intact in
#     README.md, samuel-plugin.toml's `summary`, and the registry index.toml.
#
# Usage:
#   OWNER=samuelpkg ./scripts/push-plugin-repo.sh migration-output/samuel-go-guide
#
# Bulk driver:
#   ls -1 migration-output | grep -v '^samuel-registry$' > /tmp/dirs.txt
#   while read d; do ./scripts/push-plugin-repo.sh "migration-output/$d" || echo "FAIL: $d"; done < /tmp/dirs.txt

set -euo pipefail

dir="$1"
owner="${OWNER:-samuelpkg}"
name=$(basename "$dir")

cd "$dir"

if [ ! -d .git ]; then
  git init -q -b main
fi

git add -A

if ! git diff --cached --quiet --exit-code; then
  git -c user.email="${GIT_AUTHOR_EMAIL:-angel@cuemby.com}" \
      -c user.name="${GIT_AUTHOR_NAME:-Angel Ramirez}" \
    commit -q -m "feat: initial release ($name) for Samuel v2

Generated by scripts/migrate-v1-skills from the v1 .claude/skills/ tree.

Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>"
fi

# Only tag if not present; otherwise leave the existing tag alone.
if ! git rev-parse --verify --quiet refs/tags/v1.0.0 >/dev/null; then
  git tag v1.0.0 -m "v1.0.0" >/dev/null
fi

if ! /opt/homebrew/bin/gh repo view "$owner/$name" >/dev/null 2>&1; then
  raw=$(awk 'NR==3{sub(/^> */,""); print}' README.md)
  if [ ${#raw} -le 340 ]; then
    desc="$raw"
  else
    head="${raw:0:337}"
    if [[ "$head" == *" "* ]]; then
      desc="${head% *}..."
    else
      desc="${head}..."
    fi
  fi
  /opt/homebrew/bin/gh repo create "$owner/$name" --public \
    --source=. --remote=origin --description "$desc" >/dev/null
fi

# Push, surfacing any failure (set -e catches it).
git push -u origin main --quiet
git push origin v1.0.0 --quiet
echo "  pushed: $name"
