#!/usr/bin/env bash
# Squash a single samuelpkg/samuel-<name> repo's history to one initial commit
# at v1.0.0. Force-pushes main, re-cuts the v1.0.0 tag.
#
# Why: during the initial bulk migration each plugin accumulated 2-3 extra
# commits (initial push → workflow-add patch → content-sync patch) as we
# repaired drift. The contents are correct now, but the history is noisy.
# This rewrites to a single, clean "feat: initial release" commit.
#
# Usage:
#   OWNER=samuelpkg ./scripts/squash-plugin-history.sh samuel-go-guide
#
# Bulk:
#   while read r; do ./scripts/squash-plugin-history.sh "$r" || echo "FAIL: $r"; done < /tmp/plugins.txt

set -euo pipefail

repo="$1"
owner="${OWNER:-samuelpkg}"

work=$(mktemp -d "${TMPDIR:-/tmp}/samuel-squash.XXXXXX")
trap 'rm -rf "$work"' EXIT

git clone --quiet "git@github.com:$owner/$repo.git" "$work/$repo"
cd "$work/$repo"

# Are we already a single-commit history? If so, skip.
commits=$(git rev-list --count HEAD)
if [ "$commits" = "1" ]; then
  echo "  skip: $repo (already single commit)"
  exit 0
fi

# Create an orphan branch with the same tree as HEAD; one fresh commit.
git checkout --quiet --orphan squashed
git -c user.email="${GIT_AUTHOR_EMAIL:-angel@cuemby.com}" \
    -c user.name="${GIT_AUTHOR_NAME:-Angel Ramirez}" \
  commit --quiet -m "feat: initial release ($repo) for Samuel v2

Generated by scripts/migrate-v1-skills from the v1 .claude/skills/ tree.

Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>"

# Replace main with squashed, retag v1.0.0, force-push both.
git branch --quiet -D main 2>/dev/null || true
git branch --quiet -m main
git tag -d v1.0.0 >/dev/null 2>&1 || true
git tag -a v1.0.0 -m "v1.0.0"

git push --quiet --force origin main
git push --quiet --force origin v1.0.0
echo "  squashed: $repo ($commits commits → 1)"
